# Generated by Django 6.0.6 on 2026-07-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='amount',
            field=models.IntegerField(verbose_name='monto'),
        ),
    ]
