# Generated by Django 6.0.6 on 2026-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expenseinstallment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='dark', max_length=10, verbose_name='tema'),
        ),
    ]
