# Generated by Django 6.0.6 on 2026-07-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent_color',
            field=models.CharField(choices=[('primary', 'Azul'), ('danger', 'Rojo'), ('warning', 'Naranja'), ('success', 'Verde'), ('violet', 'Violeta'), ('secondary', 'Gris')], default='primary', max_length=10, verbose_name='color de acento'),
        ),
    ]
