# Generated by Django 6.0.6 on 2026-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_accent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accent_color',
            field=models.CharField(choices=[('primary', 'Azul'), ('danger', 'Rojo'), ('warning', 'Naranja'), ('success', 'Verde'), ('secondary', 'Gris')], default='primary', max_length=10, verbose_name='color de acento'),
        ),
    ]
